# Generated by Django 5.1.7 on 2025-04-01 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatLog',
        ),
    ]
