from django.urls import path
from . import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('', views.home, name='home'),
    path('numbers/', views.numbers, name='numbers'),
    path('hiragana/', views.hiragana, name='hiragana'),
    path('katakana/', views.katakana, name='katakana'),
    path('n5/', views.n5, name='n5'),
    path('n5_quiz/', views.n5_quiz, name='n5_quiz'),
    path('n5_kanji/', views.n5_kanji, name='n5_kanji'),
    path('n4/', views.n4, name='n4'),
    path('n4_quiz/', views.n4_quiz, name='n4_quiz'),
    path('n4_kanji/', views.n4_kanji, name='n4_kanji'),
    path('n3/', views.n3, name='n3'),
    path('n3_quiz/', views.n3_quiz, name='n3_quiz'),
    path('n3_kanji/', views.n3_kanji, name='n3_kanji'),
    path('n2/', views.n2, name='n2'),
    path('n2_quiz/', views.n2_quiz, name='n2_quiz'),
    path('n2_kanji/', views.n2_kanji, name='n2_kanji'),
    path('n1/', views.n1, name='n1'),
    path('n1_quiz/', views.n1_quiz, name='n1_quiz'),
    path('n1_kanji/', views.n1_kanji, name='n1_kanji'),
    path('about/', views.about, name='about'),
    path('resources/', views.resources, name='resources'),
    path('dashboard/', views.dashboard, name='dashboard'),
    path('register/', views.register, name='register'),
    path('confirm-email/<str:token>/', views.confirm_email, name='confirm_email'),
    path('resend-confirmation/', views.resend_confirmation, name='resend_confirmation'),
    path('profile/', views.profile, name='profile'),
    path('contact/', views.contact, name='contact'),
    path('quiz/<str:level>/', views.quiz, name='quiz'),
    path('quizzes/<slug:slug>/', views.quiz, name='quiz_detail'),
    path('password_reset/', auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'), name='password_reset'),
    path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
    path('reset/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='registration/password_reset_confirm.html'), name='password_reset_confirm'),
    path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('admin-bulk-upload/', views.admin_bulk_upload, name='admin_bulk_upload'),
]