# Generated by Django 5.1.7 on 2025-03-07 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('N5', 'N5'), ('N4', 'N4'), ('N3', 'N3'), ('N2', 'N2'), ('N1', 'N1')], max_length=2)),
                ('word', models.CharField(max_length=50)),
                ('reading', models.CharField(max_length=50)),
                ('meaning', models.CharField(max_length=100)),
                ('example', models.TextField(blank=True)),
            ],
        ),
    ]
