# Generated by Django 5.1.7 on 2025-03-08 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasures', '0002_kanji_quizquestion_vocabulary_audio_userprogress'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('word', models.CharField(max_length=100)),
                ('reading', models.CharField(max_length=100)),
                ('meaning', models.CharField(max_length=255)),
                ('date', models.DateField(unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='quiz_completed',
        ),
        migrations.RemoveField(
            model_name='userprogress',
            name='studied',
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='wrong_answer3',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userprogress',
            name='lessons_completed',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='quiz_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='total_lessons',
            field=models.IntegerField(default=10),
        ),
        migrations.AddField(
            model_name='userprogress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question',
            field=models.CharField(max_length=255),
        ),
    ]
