# Generated by Django 5.1.7 on 2025-03-08 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasures', '0005_tip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailyword',
            name='meaning',
        ),
        migrations.AddField(
            model_name='dailyword',
            name='english_meaning',
            field=models.CharField(default='No meaning available', max_length=200),
        ),
    ]
