# Generated by Django 4.2.20 on 2025-03-12 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasures', '0007_uploadedfile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadedFile',
        ),
    ]
