# Generated by Django 4.2.20 on 2025-03-12 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treasures', '0008_delete_uploadedfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailyword',
            name='english_meaning',
            field=models.CharField(max_length=200),
        ),
    ]
