# Generated by Django 4.2.20 on 2025-03-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('treasures', '0009_alter_dailyword_english_meaning'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tip',
        ),
        migrations.DeleteModel(
            name='Vocabulary',
        ),
    ]
