# Generated by Django 4.2.20 on 2025-03-15 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('treasures', '0010_delete_tip_delete_vocabulary'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyKanji',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('example_sentence', models.CharField(blank=True, max_length=200)),
                ('example_translation', models.CharField(blank=True, max_length=200)),
                ('kanji', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_kanji', to='treasures.kanji')),
            ],
        ),
    ]
